
/*****
*
* Copyright (C) 2001, 2002, 2003, 2004, 2005 PreludeIDS Technologies. All Rights Reserved.
* Author: Yoann Vandoorselaere <yoannv@gmail.com>
*
* This file is part of the Requiem library.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2, or (at your option)
* any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; see the file COPYING.  If not, write to
* the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
*
*****/

/* Auto-generated by the GenerateIDMEFMessageWriteH package */

#ifndef _LIBREQUIEM_IDMEF_MESSAGE_WRITE_H
#define _LIBREQUIEM_IDMEF_MESSAGE_WRITE_H

#include "requiem-inttypes.h"
#include "idmef-time.h"
#include "requiem-string.h"
#include "requiem-msgbuf.h"

#ifdef __cplusplus
 extern "C" {
#endif

int idmef_additional_data_write(idmef_additional_data_t *additional_data, requiem_msgbuf_t *msg);
int idmef_reference_write(idmef_reference_t *reference, requiem_msgbuf_t *msg);
int idmef_classification_write(idmef_classification_t *classification, requiem_msgbuf_t *msg);
int idmef_user_id_write(idmef_user_id_t *user_id, requiem_msgbuf_t *msg);
int idmef_user_write(idmef_user_t *user, requiem_msgbuf_t *msg);
int idmef_address_write(idmef_address_t *address, requiem_msgbuf_t *msg);
int idmef_process_write(idmef_process_t *process, requiem_msgbuf_t *msg);
int idmef_web_service_write(idmef_web_service_t *web_service, requiem_msgbuf_t *msg);
int idmef_snmp_service_write(idmef_snmp_service_t *snmp_service, requiem_msgbuf_t *msg);
int idmef_service_write(idmef_service_t *service, requiem_msgbuf_t *msg);
int idmef_node_write(idmef_node_t *node, requiem_msgbuf_t *msg);
int idmef_source_write(idmef_source_t *source, requiem_msgbuf_t *msg);
int idmef_file_access_write(idmef_file_access_t *file_access, requiem_msgbuf_t *msg);
int idmef_inode_write(idmef_inode_t *inode, requiem_msgbuf_t *msg);
int idmef_checksum_write(idmef_checksum_t *checksum, requiem_msgbuf_t *msg);
int idmef_file_write(idmef_file_t *file, requiem_msgbuf_t *msg);
int idmef_linkage_write(idmef_linkage_t *linkage, requiem_msgbuf_t *msg);
int idmef_target_write(idmef_target_t *target, requiem_msgbuf_t *msg);
int idmef_analyzer_write(idmef_analyzer_t *analyzer, requiem_msgbuf_t *msg);
int idmef_alertident_write(idmef_alertident_t *alertident, requiem_msgbuf_t *msg);
int idmef_impact_write(idmef_impact_t *impact, requiem_msgbuf_t *msg);
int idmef_action_write(idmef_action_t *action, requiem_msgbuf_t *msg);
int idmef_confidence_write(idmef_confidence_t *confidence, requiem_msgbuf_t *msg);
int idmef_assessment_write(idmef_assessment_t *assessment, requiem_msgbuf_t *msg);
int idmef_tool_alert_write(idmef_tool_alert_t *tool_alert, requiem_msgbuf_t *msg);
int idmef_correlation_alert_write(idmef_correlation_alert_t *correlation_alert, requiem_msgbuf_t *msg);
int idmef_overflow_alert_write(idmef_overflow_alert_t *overflow_alert, requiem_msgbuf_t *msg);
int idmef_alert_write(idmef_alert_t *alert, requiem_msgbuf_t *msg);
int idmef_heartbeat_write(idmef_heartbeat_t *heartbeat, requiem_msgbuf_t *msg);
int idmef_message_write(idmef_message_t *message, requiem_msgbuf_t *msg);


#ifdef __cplusplus
 }
#endif

#endif /* _LIBREQUIEM_IDMEF_MESSAGE_WRITE_H */
